	<div class="politica" >
		<h2>USO Y RESTRICCIONES.</h2>
			<p>La utilizaci&oacute;n del portal Online Store&reg; (&#8220;Portal&#8221;) expresa la adhesi&oacute;n plena y sin reservas del usuario a los presentes T&eacute;rminos y Condiciones de Uso y Privacidad. A trav&eacute;s del Portal, el usuario accesar&aacute; y/o utilizar&aacute; diversos servicios y contenidos (en losucesivo, los &#8220;Servicios y Contenidos&#8221;), puestos a disposici&oacute;n de los usuarios por Online Store&reg;, S.C. y/o sus subsidiarias y afiliadas , y/o por terceros proveedores de Servicios y Contenidos. Online Store&reg; tendr&aacute; el derecho a negar, restringir o condicionar al usuario el acceso al Portal, total o parcialmente, a su entera discreci&oacute;n, as&iacute; como a modificar los Servicios y Contenidos del Portal, en cualquier momento y sin necesidad de previo aviso.</p>
		<br /><br />
			<p>Online Store&reg;  no garantiza la disponibilidad y continuidad de la operaci&oacute;n del Portal y de los Servicios y Contenidos, ni la utilidad del Portal o los Servicios y Contenidos en relaci&oacute;n con ninguna actividad espec&iacute;fica. Online Store&reg; no ser&aacute; responsable por ning&uacute;n da&ntilde;o o p&eacute;rdida de cualquier naturaleza que pueda ser causado debido a la falta de disponibilidad o continuidad de operaci&oacute;n del Portal y/o de los Servicios y Contenidos.</p>
		<h3>1. PROPIEDAD INTELECTUAL.</h3>
			<p>Los derechos de propiedad intelectual respecto de los Servicios y Contenidos y los signos distintivos y dominios del Portal, as&iacute; como los derechos de uso y explotaci&oacute;n de los mismos, incluyendo su divulgaci&oacute;n, publicaci&oacute;n, reproducci&oacute;n, distribuci&oacute;n y transformaci&oacute;n, son propiedad exclusiva de Online Store&reg;. El usuario no adquiere ning&uacute;n derecho de propiedad intelectual por el simple uso de los Servicios y Contenidos del Portal y en ning&uacute;n momento dicho uso ser&aacute; considerado como una autorizaci&oacute;n ni licencia para utilizar los Servicios y Contenidos con fines distintos a los que se contemplan en los presentes T&eacute;rminos y Condiciones de Uso y Privacidad.</p>
		<h3>3. PROPIEDAD INTELECTUAL DE TERCEROS.</h3>
			<p>El usuario acuerda que las disposiciones que se establecen en el inciso 2 anterior respecto de la titularidad de los derechos de Online Store&reg; tambi&eacute;n son aplicables a los derechos de terceros respecto de los Servicios y Contenidos de las p&aacute;ginas enlazadas al Portal.</p>
		<h3>2. USOS PERMITIDOS.</h3>
			<p>El aprovechamiento de los Servicios y Contenidos del Portal es exclusiva responsabilidad del usuario, quien en todo caso deber&aacute; servirse de ellos acorde a las funcionalidades permitidas en el propio Portal y a los usos autorizados en los presentes T&eacute;rminos y Condiciones de Uso y Privacidad, por lo que el usuario se obliga a utilizarlos de modo tal que no atenten contra las normas de uso y convivencia en Internet, las leyes de los Estados Unidos Mexicanos y la legislaci&oacute;n vigente en el pa&iacute;s en que el usuario se encuentre al usarlos, las buenas costumbres, la dignidad de la persona y los derechos de terceros. El Portal es para el uso personal y del usuario por lo que no podr&aacute; comercializar de manera alguna los Servicios y Contenidos.</p>
		<h3>3. PROHIBICIONES.</h3>
			<p>El usuario no tiene el derecho de colocar hiperligas de y al Portal, ni el derecho de colocar o utilizar los Servicios y Contenidos del Portal en sitios o p&aacute;ginas propias o de terceros sin autorizaci&oacute;n previa y por escrito de Online Store&reg;. Asimismo, el usuario no tendr&aacute; el derecho de limitar o impedir a cualquier otro usuario el uso del Portal.</p>
		<h3>4. CALIDAD DE LOS SERVICIOS Y CONTENIDOS.</h3>
			<p>Ni Online Store&reg;, ni sus proveedores o socios comerciales ser&aacute;n responsables de cualquier da&ntilde;o o perjuicio que sufra el usuario a consecuencia de inexactitudes, errores tipogr&aacute;ficos y cambios o mejoras que se realicen peri&oacute;dicamente a los Servicios y Contenidos. Las recomendaciones y consejos obtenidos a trav&eacute;s del Portal son de naturaleza general, por lo que no deben tomarse en cuenta en la adopci&oacute;n de decisiones personales. Para ello se debe consultar a un profesional apropiado que pueda asesorar al usuario de acuerdo con sus necesidades espec&iacute;ficas.</p>
		<h3>5. BIENES Y SERVICIOS DE TERCEROS ENLAZADOS.</h3>
			<p>Respecto de los Servicios y Contenidos que prestan terceros dentro o mediante enlaces al Portal (tales como ligas, banners y botones), Online Store&reg; se limita exclusivamente, para conveniencia del usuario, a: (i) informar al usuario sobre los mismos, y (ii) a proporcionar un medio para poner en contacto al usuario con proveedores o vendedores. Los productos y/o servicios que se comercializan dentro del Portal y/o en los sitios de terceros enlazados son suministrados por comerciantes independientes a Online Store&reg;. Online Store&reg; no es ni podr&aacute; ser considerado como proveedor de los bienes y/o servicios que se ofrecen en dichas p&aacute;ginas y/o sitios. La inclusi&oacute;n de dichas p&aacute;ginas y/o enlaces no implica la aprobaci&oacute;n, respaldo, patrocinio, recomendaci&oacute;n o garant&iacute;a, por parte de Online Store&reg;, de los servicios y bienes que se comercializan en los mismos ni del contenido de dichas p&aacute;ginas. No existe ning&uacute;n tipo de relaci&oacute;n laboral, asociaci&oacute;n o sociedad, entre Online Store&reg; y dichos terceros. Toda asesor&iacute;a, consejo, declaraci&oacute;n, informaci&oacute;n y contenido de las p&aacute;ginas de terceros enlazadas o dentro del Portal representan las opiniones y juicios de dicho tercero, consecuentemente, Online Store&reg; no ser&aacute; responsable de ning&uacute;n da&ntilde;o o perjuicio que sufra el usuario a consecuencia de los mismos, incluyendo, de manera enunciativa mas no limitativa, da&ntilde;os causados por la p&eacute;rdida de datos o programas.</p>
		<h3>6. CONFIDENCIALIDAD.</h3>
			<p>Online Store&reg;  se obliga a mantener confidencial la informaci&oacute;n que reciba del usuario que tenga dicho car&aacute;cter conforme a las disposiciones legales aplicables, en los Estados Unidos Mexicanos. Online Store&reg; no asume ninguna obligaci&oacute;n de mantener confidencial cualquier otra informaci&oacute;n que el usuario le proporcione, ya sea al inscribirse al Portal o en cualquier otro momento posterior, incluyendo aquella informaci&oacute;n que el usuario proporcione a trav&eacute;s de boletines, pizarras o pl&aacute;tica en l&iacute;nea (chats), as&iacute; como la informaci&oacute;n que Online Store&reg; a trav&eacute;s de las Cookies que se describen en el inciso 11.</p>
		<h3>7. PROGRAMA DE PRIVACIDAD DE MAZARI CONSULTIN GROUP.</h3>
			<p>La seguridad de su informaci&oacute;n personal es nuestra prioridad. Nosotros protegemos esta informaci&oacute;n mediante el mantenimiento de protecciones f&iacute;sicas, electr&oacute;nicas y de procedimiento que cumplen o exceden lo previsto en la legislaci&oacute;n aplicable. Nosotros capacitamos a nuestros empleados en el manejo adecuado de la informaci&oacute;n personal. Al utilizar otras compa&ntilde;&iacute;as para que nos presten servicios, les exigimos proteger la confidencialidad de la informaci&oacute;n personal que ellos reciban.</p>
		<h3>8. USO DE LA INFORMACI&Oacute;N NO CONFIDENCIAL.</h3>
			<p>Mediante el uso del Portal, el usuario autoriza a Online Store&reg; a utilizar, publicar, reproducir, divulgar, comunicar p&uacute;blicamente y transmitir la informaci&oacute;n no confidencial, en t&eacute;rminos de lo establecido en el art&iacute;culo 109 de la Ley Federal de los Derechos de Autor y de la fracci&oacute;n I, del art&iacute;culo 76 bis de la Ley Federal de Protecci&oacute;n al Consumidor.</p>
		<h3>9. COOKIES.</h3>
			<p>El usuario que tenga acceso al Portal, acuerda recibir las cookies que les transmitan los servidores de Online Store&reg;. &#8220;Cookie&#8221; significa un archivo de datos que se almacena en el disco duro de la computadora del usuario cuando &eacute;ste tiene acceso al Portal. Las Cookies pueden contener informaci&oacute;n tal como la identificaci&oacute;n proporcionada por el usuario o informaci&oacute;n para rastrear las p&aacute;ginas que el usuario ha visitado. Una Cookie no puede leer los datos o informaci&oacute;n del disco duro del usuario ni leer las Cookies creadas por otros sitios o p&aacute;ginas.</p>
		<h3>10. CLAVES DE ACCESO Y NUMEROS CONFIDENCIALES.</h3>
			<p>En todo momento, el usuario es el responsable &uacute;nico y final de mantener en secreto la identificaci&oacute;n de su usuario, contrase&ntilde;as personales, claves de acceso y otros datos confidenciales con los cuales tenga acceso a los Servicios y Contenidos del Portal, as&iacute; como a las p&aacute;ginas de terceros.</p>
		<h3>11. MODIFICACIONES.</h3>
			<p>Online Store&reg; tendr&aacute; el derecho de modificar en cualquier momento los T&eacute;rminos y Condiciones de Uso y Privacidad. En consecuencia, el usuario debe leer atentamente los T&eacute;rminos y Condiciones de Uso y Privacidad cada vez que pretenda utilizar el Portal. Ciertos Servicios y Contenidos ofrecidos a los usuarios en y/o a trav&eacute;s del Portal est&aacute;n sujetos a condiciones particulares propias que sustituyen, completan y/o modifican los T&eacute;rminos y Condiciones de Uso y Privacidad (en lo sucesivo, las &#8220;Condiciones Particulares&#8221;). Consiguientemente, el usuario tambi&eacute;n debe leer atentamente las correspondientes Condiciones Particulares antes de acceder a cualesquiera Servicios y Contenidos.</p>
		<h3>12. LEYES APLICABLES Y JURISDICCI&Oacute;N.</h3>
			<p>Para la interpretaci&oacute;n, cumplimiento y ejecuci&oacute;n del presente Contrato, las partes est&aacute;n de acuerdo en que ser&aacute;n aplicables las leyes Federales de los Estados Unidos Mexicanos y competentes los tribunales de la Ciudad de M&eacute;xico, Distrito Federal, renunciando expresamente a cualquier otro fuero o jurisdicci&oacute;n que pudiera corresponderles en raz&oacute;n de sus domicilios presentes o futuros.</p>
		<h3>13. COMENTARIOS, MENSAJES Y BLOGS.</h3>
			<p>Para que tu participaci&oacute;n comentando nuestros art&iacute;culos, foros de mensajes y blogs sea una experiencia positiva, te pedimos que revises y aceptes los T&eacute;rminos y Condiciones y a las Reglas que tenemos para comentar en nuestras p&aacute;ginas. Las opiniones de los usuarios as&iacute; como de los blogueros y columnistas no representan necesariamente el punto de vista de mazarigroup.com ni de Online Store&reg;. El simple hecho de haber participado en las discusiones o enviar tus comentarios en el portal, damos por sentado que has aceptado tales T&eacute;rminos.</p>
		<br /><br />
		<ul>
			<li>A). T&uacute; eres el &uacute;nico responsable del contenido que ofreces. No podr&aacute;s aportar ning&uacute;n contenido que viole los derechos de autor, marca y/o, patentes u otros derechos de propiedad intelectual de terceras personas. De entenderse que no cumplas con esta disposici&oacute;n tu contenido puede ser removido. Es muy importante que no env&iacute;es contenido que caiga en el libelo, difamaci&oacute;n, obscenidad, que viole la privacidad de terceras personas o que viole cualquier ley aplicable o que resulte de otro modo inapropiado. De incurrir en alguna violaci&oacute;n de esta naturaleza, te comprometes a indemnizar a Online Store&reg; sus empleados, agentes y afiliadas de cualquier reclamaci&oacute;n o da&ntilde;o incluyendo los honorarios de abogados, que resulten derivados de cualquier reclamaci&oacute;n de cualquier persona relacionada al contenido aportado por ti. Te pedimos que seas consciente de que en estos foros no podr&aacute;s aportar contenido que degrade a otros por sexo, raza, clase social, nacionalidad, religi&oacute;n, preferencia sexual, incapacidad o cualquier otra clasificaci&oacute;n que afecte a terceros. No ser&aacute; aceptado ning&uacute;n lenguaje que tenga la intenci&oacute;n de intimidar o a incitar a la violencia.</li>
			<li>B). Est&aacute;s de acuerdo que Online Store&reg; no es responsable del contenido aportado por terceras personas. Aceptando la posibilidad de que todos los usuarios tienen el derecho de opinar, es importante que reconozcas que no necesariamente se monitorean los contenidos aportados en espacios interactivos. Sin embargo, www.cnnexpansion.com pudiera monitorear el contenido aportado por los Usuarios a discreci&oacute;n y se reserva el derecho de remover, editar o alterar el contenido que estime inapropiado sin su consentimiento. Online Store&reg; tambi&eacute;n se reserva el derecho a cancelar el privilegio de los Usuarios a aportar contenido en su sitio en cualquier momento y sin previo aviso.</li>
			<li>C). Reconoces y aceptas que los comentarios no deben ser utilizados con prop&oacute;sitos comerciales o dirigidos a menores. Est&aacute; terminantemente prohibido hacer publicidad, propaganda, solicitaci&oacute;n de fondos o de otro modo promover entidades o actividades comerciales en el &aacute;rea de comentarios. Del mismo modo, queda prohibido hacer enlaces, publicidad o propaganda a sitios no aptos para menores, de origen pornogr&aacute;fico, inmorales, etc.</li>
			<li>D). Reconoces y aceptas que si usas informaci&oacute;n obtenida a trav&eacute;s de los espacios interactivos ser&aacute; bajo tu s&oacute;lo riesgo. Online Store&reg; no se hace responsable ni se solidariza ni endosa los contenidos aportados por los Usuarios, ni da fe de su correcci&oacute;n y veracidad. Este es s&oacute;lo un espacio para interactuar y compartir ideas entre usuarios.</li>
			<li>E). Otorgas a Online Store&reg; la licencia sobre el contenido aportado. Por el mero hecho de aportar informaci&oacute;n y/o contenido a trav&eacute;s del &aacute;rea de comentarios, est&aacute;s otorgando a Online Store&reg; un derecho de licencia perpetua, no exclusiva, gratuita y de alcance mundial para reproducir, almacenar, editar, modificar, publicar, incorporar en bases de datos, comunicar p&uacute;blicamente, sub-licenciar, transmitir, distribuir, representar, o en cualquier otra forma explotar comercialmente, en todo o en parte, tales contenidos en cualquier forma y/o a trav&eacute;s de cualquier medio o tecnolog&iacute;a conocido o por conocerse.</li>
		</ul>
	</div>